/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ArtifactBytes {
  dataBase64: string
  sizeBytes: number
}

export interface CheckCodeRuntimeSessionInput {
  traceparent?: string
  image: string
}

export interface CheckDaggerSessionInput {
  traceparent?: string
}

export interface CodeRun {
  stdout: string
  stderr: string
  exitCode: number
  timedOut: boolean
  truncated: boolean
}

export interface CodeRuntimeLimits {
  maxOutputBytes: number
  maxCpuSeconds: number
  maxMemoryBytes: number
  maxProcesses: number
}

export interface CommandExecution {
  stdout: string
  stderr: string
  exitCode: number
  durationMs: number
  timedOut: boolean
  truncated: boolean
}

export interface Limits {
  outputBytesLimit: number
  fileSizeLimitBytes: number
  cpuSeconds: number
  memoryBytes: number
  maxProcesses: number
}

export interface ReadSandboxArtifactInput {
  traceparent?: string
  image: string
  defaultCwd: string
  aptPackages: Array<string>
  snapshots: Array<SnapshotFile>
  replayCommands: Array<ReplayCommand>
  limits: Limits
  path: string
}

export interface ReplayCommand {
  command: string
  cwd?: string
  timeoutSeconds: number
}

export interface RunCodeInput {
  traceparent?: string
  image: string
  runnerScript: string
  code: string
  requirements: Array<string>
  timeoutSeconds: number
  limits: CodeRuntimeLimits
}

export interface RunSandboxCommandInput {
  traceparent?: string
  image: string
  defaultCwd: string
  aptPackages: Array<string>
  snapshots: Array<SnapshotFile>
  replayCommands: Array<ReplayCommand>
  limits: Limits
  command: string
  cwd: string
  timeoutSeconds: number
}

export interface SnapshotFile {
  skillName: string
  path: string
  encoding: string
  content: string
}
export declare function checkCodeRuntimeSession(input: CheckCodeRuntimeSessionInput): Promise<void>

export declare function checkDaggerSession(input?: CheckDaggerSessionInput | undefined | null): Promise<void>

export declare function readSandboxArtifact(input: ReadSandboxArtifactInput): Promise<ArtifactBytes>

export declare function runCodeRuntime(input: RunCodeInput): Promise<CodeRun>

export declare function runSandboxCommand(input: RunSandboxCommandInput): Promise<CommandExecution>
